export const ROUTES = {
  FEED: "/feed",
  EVENTS: "/events",
  EVENT_DETAIL: (id: string) => `/events/${id}`,
  MISSIONS: "/missions",
  MISSION_DETAIL: (id: string) => `/missions/${id}`,
  FORUM: "/forum",
  FORUM_THREAD: (id: string) => `/forum/${id}`,
  COMMUNITY: "/community",
  MEMBERS: "/members",
  MEMBER_PROFILE: (id: string) => `/members/${id}`,
  BLOG: "/blog",
  BLOG_POST: (slug: string) => `/blog/${slug}`,
  CAPSULES: "/capsules",
  CAPSULE_DETAIL: (id: string) => `/capsules/${id}`,
  RECOMMENDED: "/recommended",
  TOOLS: "/tools",
  PROFILE: "/profile",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_CONTENT: "/admin/content",
  ADMIN_EVENTS: "/admin/events",
} as const;
